server:
  port: 10091

spring:
  application:
    name: matrixiot-service-alarm
  cloud:
    nacos:
      config:
        username: nacos
        password: nacos
        contextPath: /nacos
        server-addr: 127.0.0.1:8848
        group: spring
      discovery:
        username: nacos
        password: nacos
        server-addr: 127.0.0.1:8848
        namespace: ${spring.profiles.active}
        group: spring
  data:
    mongodb:
      uri: mongodb://root:example@127.0.0.1:27017,127.0.0.1:27018/matrixiot?authSource=admin&authMechanism=SCRAM-SHA-1&replicaSet=rs0
      auto-index-creation: true
  config:
    import: optional:nacos:test.yaml
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# alarm 应用属性
# 腾讯企业邮箱，user 属性需要和 from 一致；且需要在打开安全登录后，使用客户端专用密码
# 当前用的账号，每天最多发送500条邮件
alarm:
  email:
    host: smtp.exmail.qq.com
    port: 465
    from: iswater 物联网平台 <system.iot@hxiswater.com>
    pass: 5vYwMZHH5t7cPfpo
    user: system.iot@hxiswater.com
    test-api-enabled: true

dubbo:
  application:
    name: matrixiot-service-alarm-dubbo
    register-mode: instance
    qos-enable: false
  registry:
    address: nacos://127.0.0.1:8848?namespace=${spring.profiles.active}
    username: nacos
    password: nacos
    group: dubbo
  config-center:
    address: nacos://127.0.0.1:8848?namespace=${spring.profiles.active}
    username: nacos
    password: nacos
  consumer:
    check: false
  protocol:
    name: dubbo
    serialization: hessian2
    port: -1
    server: netty4
  scan:
    base-packages: com.victorlamp.matrixiot.service

rocketmq:
  consumer:
    group: springboot_consumer_group
    # 一次拉取消息最大值，注意是拉取消息的最大值而非消费最大值
    pull-batch-size: 10
  name-server: 127.0.0.1:9876
  producer:
    # 发送同一类消息的设置为同一个group，保证唯一
    group: springboot_producer_group
    # 发送消息超时时间，默认3000
    sendMessageTimeout: 10000
    # 发送消息失败重试次数，默认2
    retryTimesWhenSendFailed: 2
    # 异步消息重试此处，默认2
    retryTimesWhenSendAsyncFailed: 2
    # 消息最大长度，默认1024 * 1024 * 4(默认4M)
    maxMessageSize: 4096
    # 压缩消息阈值，默认4k(1024 * 4)
    compressMessageBodyThreshold: 4096
    # 是否在内部发送失败时重试另一个broker，默认false
    retryNextServer: false

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    persistAuthorization: true


logging:
  file:
    name: logs/${spring.application.name}.log