# Use root/root as user/password credentials
services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - matrixiot_dev_net
    volumes:
      - ./data:/data # 可选，用于持久化Redis数据
    command: redis-server --appendonly yes # 可选，开启持久化选项
    restart: always
    environment:
      - REDIS_PASSWORD=root
      - TZ=Asia/Shanghai
    deploy:
      resources:
        limits:
          memory: 256M
networks:
  matrixiot_dev_net:
    external: true

