services:
  grafana:
    container_name: grafana
    image: grafana/grafana:10.2.5
    volumes:
      - ./data/grafana:/var/lib/grafana
      - ./etc/grafana:/etc/grafana
    ports:
      - "3000:3000"
    environment:
      - TZ=Asia/Shanghai
    networks:
      - matrixiot_dev_net
    restart: on-failure
networks:
  matrixiot_dev_net:
    external: true
