services:
  nacos:
    container_name: nacos-standalone-mysql
    build:
      context: .
      dockerfile: Dockerfile
    image: matrixiot/nacos-server:2.2.0
    env_file:
      - ./env/nacos-standalone-mysql.env
    volumes:
      - ./standalone-logs/:/home/nacos/logs
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "8848:8848"
      - "9848:9848"
    networks:
      - matrixiot_dev_net
    restart: always
networks:
  matrixiot_dev_net:
    external: true
